dependencies {
    implementation project(':customclaims-core')
    implementation project(':customclaims-protection')

    compileOnly("maven.modrinth:create:${create_version}") { transitive = false }
    compileOnly("net.createmod.catnip:Catnip-NeoForge-1.21.1:${catnip_version}") { transitive = false }
    compileOnly("net.createmod.ponder:Ponder-NeoForge-1.21.1:${ponder_version}") { transitive = false }
}
